### ISSUE TITLE
[Bug] AutoWidget Not Functioning on Kodi 19.4 Matrix UWP (On Xbox)

### ISSUE THREAD

**Issue by ehxactly** [drinfernoo/plugin.program.autowidget#136]
**Describe the bug**
I have tried multiple times, on multiple fresh installs and repeatedly get "error with autowidget" appearing. This causes the widgets I make to appear with a 'Refresh symbol' and no results from for example Seren.

**To Reproduce**
1.  Install Kodi on Xbox (In this case I side-loaded it with a dev account)
2.  Install autowidget add-on
3.  Exit application and re-open
4.  See error

**Expected behavior**
The application should not have an error prompt and should load the autowidget results. This works fine on my Amazon Firestick for example.

**Details:**
  - What version of Kodi? 19.4 Matrix UWP
  - What skin is being used? Default, Emby, Arctic Horizon 2, Auramod
  - What device? Xbox One S
  - What platform? Windows UWP
  - LOG: https://paste.kodi.tv/qufezuroca

**Comment by Loroskii** [comment]
I'm  having the same issue, tried AutoWidget on windows and it perfectly fine, but on Xbox I tried 2 times with fresh installs of kodi, it still gives the same error, I read somewhere it's due to xbox access restriction of some python package, but don't know how to work around that.

**Comment by Brillyz** [comment]
I'm  having the same issue, tried AutoWidget on windows and it worked perfectly fine, but on Xbox I tried 2 times with fresh installs of kodi and it still gives the same error, I read somewhere it's due to Xbox access restriction of some python package, but don't know how to work around that.
Log: https://paste.kodi.tv/deqowineko

**Comment by djay** [comment]
Seems to be related to one of the bugs fixed in https://github.com/drinfernoo/plugin.program.autowidget/pull/108. Try the beta build and see if that fixes it. I don't think it's related to access restrictions on packages but just random corruption of the json files and handling that better

**Comment by Brillyz** [comment]
> Seems to be related to one of the bugs fixed in #108. Try the beta build and see if that fixes it. I don't think it's related to access restrictions on packages but just random corruption of the json files and handling that better

Where is the beta version available? as listed on the kodi forum and on this github, there are only stable and dev builds available, I tried the dev build as well and still it didn't work, if you could give me any tips I'd be grateful.

**Comment by djay** [comment]
Sorry I meant the dev build. However there is an issue that the dev build is the last PR with a commit rather than an integration branch so it's hard to tell if the current dev build has the code that fixes the issue or not. @drinfernoo should know.

**Comment by drinfernoo** [comment]
@Loroskii Can you try the `3.7.0` release? That should have all of the changes form the outstanding PRs.

**Comment by Brillyz** [comment]
@drinfernoo sorry for the late response, I checked the 3.7.0 release twice now with a fresh install of Kodi again, this time the widget error does not come up on Kodi notification when launching Kodi or trying to use the addon, so that is fixed, but still the widgets don't show on the main screen, they only show refresh icon, and when I do click the widget to refresh, it just keeps loading and nothing happens.
This is the log file and thank you for your work <3
https://paste.kodi.tv/ujeyujeyuj

**Comment by djay** [comment]
@drinfernoo maybe there are skins where the widget_id is unknown? What to do in such cases?

**Comment by djay** [comment]
@Loroskii I don't have a setup to test your case where there is no widget_id associated with a list. But I created a PR that should fix it. Try the dev build https://github.com/drinfernoo/plugin.program.autowidget/pull/137

**Comment by Brillyz** [comment]
@djay Thank you so much, I tried the updated dev build and it works perfectly fine now.

**Comment by djay** [comment]
Did you try the debug build to see if that works better?
