### ISSUE TITLE
[Enhancement/Bug] Find Solution for ListItem Properties

### ISSUE THREAD

**Issue by drinfernoo** [drinfernoo/plugin.program.autowidget#31]
https://forum.kodi.tv/showthread.php?tid=354817&pid=2953291#pid2953291

**Comment by jurialmunkey** [comment]
@drinfernoo Continuing our discussion from this issue: https://github.com/jurialmunkey/script.skinvariables/issues/4

> I've made a window positioned offscreen, but it definitely still steals focus, though I am calling it with doModal()... because it has work that needs to be done before the calling method can continue.

Yeah I think any script calling a window/dialog is going to steal focus because ActivateWindow sets focus to default control in the window/dialog.

Also, `doModal()` is the opposite of what you want. I used to think the same that a modal dialog was just a dialog kept in a separate instance, but I recently found out that a modal window disables interaction with the underlying parent window (but keeps it visible) forcing the user to interact with the modal child window. So basically DialogBusy and DialogProgress are modal, whilst DialogProgressBG and DialogVolumeBar are modeless.
https://en.wikipedia.org/wiki/Modal_window

You want a "modeless" window. According to this [comment](https://forum.kodi.tv/showthread.php?tid=106998&pid=856351#pid856351) `show()` will give you a modeless window. I haven't tested, so it is possible that it might still steal focus due to being activated. Might be worth a try though. https://codedocs.xyz/AlwinEsch/kodi/group__python__xbmcgui__window.html#ga051a2bdfbd8f003c55144e5347fbd3a4

> Unfortunately, this control I need to access is a list control, populated via a <content> tag, so that it can have dynamic content. As far as I can tell, there is no way to do this with a Python ControlList, unless I create the items to populate it with beforehand.

Yeah, you're right. You can only add static content, not dynamic content - I forgot I had that same issue when making the TMDbHelper info dialog window manager.

---

Another option is a Custom window in the skin and then you just make it visible using a Window Property / Skin Variable. Would require skins to specifically support AutoWidget though.

**Comment by drinfernoo** [comment]
I thought that maybe `show()` would be the way to go in the end... but had never figured out how to make it wait.

I thought maybe something like in: https://github.com/drinfernoo/plugin.program.example/commit/d8106955c9dd5385ab0699228d2c6fa402a2b6ec, where I simply wait for the window property to be "recycled"... but in testing, this seems to not only block the UI until *all* of the windows have finished, but also can completely freeze Kodi.

If I point more than two widgets at "Test Mock Window" in that example script above, Kodi will completely freeze, needing to be force closed. Maybe each of them should be run in a thread?

**Comment by drinfernoo** [comment]
Getting there: https://forum.kodi.tv/showthread.php?tid=355209&pid=2959827#pid2959827 😁

**Comment by drinfernoo** [comment]
Even closer! https://github.com/xbmc/xbmc/pull/18106
