### ISSUE TITLE
[Feature Request] Allow to Set Content of Sections

### ISSUE THREAD

**Issue by drinfernoo** [drinfernoo/plugin.program.autowidget#41]
https://forum.kodi.tv/showthread.php?pid=2970071#pid2970071

**Comment by jmh2002** [comment]
Any progress on this issue from way back in August last year? I switched to a new skin recently (Madnox) and the necessary view isn't available for Auto Widget items because, I suppose, content isn't being set correctly?

In this case they are YouTube videos. If I view the same items in YouTube I can change the Skin View. But once they are brought into an AutoWidget list and merged, I can't.

**Comment by drinfernoo** [comment]
There have been no updates on this issue, no. It should be relatively obvious, as the issue is still open, and there have been no comments.

**Comment by jmh2002** [comment]
Thanks, I just wanted to make sure that I hadn't missed something since this issue appeared to become apparent after changing skins. Looking forward to updates in due course :)

**Comment by drinfernoo** [comment]
@jmh2002 I've implemented this in the `develop` branch, and it seems to be working fine for me... with the exception that it won't support *groups* made prior to what will be version 3.3.0 when it releases. If you want to set the content type of what will then be considered a "legacy" group, you'll need to recreate the group. After that, it will be settable from AutoWidget's context menu editor dialog.

Paths should be supported, but unless you are linking directly to a path, rather than showing it as a widget, this seems less useful 😅

**Comment by jmh2002** [comment]
Ok thanks for the continued development :)
